### ISSUE TITLE
Bug: Maya Repair Frame Range 

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [ynput/OpenPype#4850] opened 2023-04-18 09:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

There is a regression of issue with running Repair Action on `Validate Frame Range` with `model` instance nested under `review`

### Version

3.15.4-nightly.3

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

![image](https://user-images.githubusercontent.com/352795/232741124-6c1cc29f-15cb-44d9-bd4f-3e3f20b4b9bf.png)

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
plugin is: <class 'D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\validate_frame_range.py.ValidateFrameRange'>
b"Preparing <class 'openpype.pipeline.publish.publish_plugins.RepairAction'>.."
b'Action prepared.'
# # ERROR - Traceback (most recent call last):
#   File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
#     runner(*args)
#   File "D:\REPO\OpenPype\openpype\pipeline\publish\publish_plugins.py", line 242, in process
#     plugin.repair(instance)
#   File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\validate_frame_range.py", line 138, in repair
# RuntimeError: setAttr: No object matches name: modelMain.frameStart
# 
# Traceback (most recent call last):
#   File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
#     runner(*args)
#   File "D:\REPO\OpenPype\openpype\pipeline\publish\publish_plugins.py", line 242, in process
#     plugin.repair(instance)
#   File "<string>", line 138, in repair
# RuntimeError: setAttr: No object matches name: modelMain.frameStart

// Error: pyblish.plugin : Traceback (most recent call last):
  File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "D:\REPO\OpenPype\openpype\pipeline\publish\publish_plugins.py", line 242, in process
    plugin.repair(instance)
  File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\validate_frame_range.py", line 138, in repair
RuntimeError: setAttr: No object matches name: modelMain.frameStart

Traceback (most recent call last):
  File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "D:\REPO\OpenPype\openpype\pipeline\publish\publish_plugins.py", line 242, in process
    plugin.repair(instance)
  File "<string>", line 138, in repair
RuntimeError: setAttr: No object matches name: modelMain.frameStart
 //
```

[cuID:[OP-5715](https://app.clickup.com/t/863ggy5yy)]

**Comment by BigRoy** [comment] 2023-04-18 10:46
It seems like this issue that was reported before https://github.com/ynput/OpenPype/issues/2562 popped up again or was never fixed to begin with? Duplicate maybe?

**Comment by tokejepsen** [comment] 2023-04-18 11:07
Being able to repair the plugin `ValidateFrameRange` should not happen for case of `model` instance nested under `review`. It will be excluded [here](https://github.com/ynput/OpenPype/blob/develop/openpype/settings/defaults/project_settings/maya.json#L728-L732). The reason why it was failing was because of this error;

```

Instance: 
modelMain
Message: 
int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Line: 
62
Traceback: 
Traceback (most recent call last):
  File "C:\Users\tokejepsen\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "C:\Users\tokejepsen\OpenPype\openpype\hosts\maya\plugins\publish\validate_frame_range.py", line 62, in process
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

This is fixed with https://github.com/tokejepsen/pype/commit/38cc309d43613e78d94ee7e9bbf53b1044b713be (sorry wrong issue referenced).

**Comment by tokejepsen** [comment] 2023-04-18 11:08
Reopen if we think it needs fixing somehow.

**Closed by tokejepsen** 2023-04-18 11:08 UTC
Labels: type: bug, host: Maya

**Comment by m-u-r-p-h-y** [comment] 2023-04-18 12:42
It's passing now even though it should not?

![image](https://user-images.githubusercontent.com/352795/232780459-198b205e-ab36-4c47-a905-7fbe7da728a6.png)

**Comment by tokejepsen** [comment] 2023-04-18 13:04
Yeah, this is intended behaviour due to the `exclusion_families` in https://github.com/ynput/OpenPype/blob/develop/openpype/settings/defaults/project_settings/maya.json#L728-L732

**Comment by tokejepsen** [comment] 2023-04-18 13:36
> so the parent review instance is not getting validated?

Yeah, its completely ignore by `ValidateFrameRange`. TBH no idea why this logic is in there. Was added here by a former Ynput employee; https://github.com/ynput/OpenPype/commit/c762fa92f6ab7f692c751fefdffe5f9c9571d582
