### ISSUE TITLE
Maya: Move capture.py to host directory

### ISSUE THREAD

**Issue by tokejepsen** [ynput/OpenPype#4767] opened 2023-04-03 11:57 UTC
**Describe the solution you'd like**
Since `capture.py` is Maya specific, it should be under the host directory.

**Additional context**
Blender also has a `capture.py` module under its host directory.

[cuID:863gd0nu1]

**Comment by BigRoy** [comment] 2023-04-03 12:00
This appears to be a duplicate of https://github.com/ynput/OpenPype/issues/4696

**Closed** 2023-04-03 12:35 UTC
Labels: type: enhancement, host: Maya, type: refactor
