### ISSUE TITLE
TrayMenu: changelog link

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#1723] opened 2021-06-17 09:55 UTC
# Description
At the moment the only way to get to change log is to open CHANGELOG.md fille in OpenPype codebase (not everyone knows how to get there) or find it on Github (also not everyone knows how to). 

# Solution
Easiest way would be to have the Github link available at our OpenPype info widget (TrayMenu). This link would open Githhub page in web brouwser. 

![image](https://user-images.githubusercontent.com/40640033/122374694-e3c4c400-cf62-11eb-855e-324b4e329b8f.png)

[cuID:[OP-1133](https://app.clickup.com/t/yjxyce)]

**Comment by BigRoy** [comment] 2023-07-01 14:38
I didn't even know there was a changelog link. So I went to that part in UI and there was none:

![image](https://github.com/ynput/OpenPype/assets/2439881/df613981-5883-4a28-8581-f89741926f77)

I suppose there isn't any nowadays?

**Comment by mkolar** [comment] 2023-07-04 09:35
Well. that's exactly what the issue is about. Adding one :)

**Comment by BigRoy** [comment] 2023-07-04 09:40
I must have been reading this with my eyes closed - you are right, of course.

**Comment by mkolar** [comment] 2023-10-19 16:45
Considering this had no traction since start and it'll become more complex than this in AYON (addons split to multiple repos with their own changelogs). I'm closing this.

**Closed by mkolar** 2023-10-19 16:45 UTC
Labels: type: enhancement, sponsored, Good first issue
