### ISSUE TITLE
Blender: Update to latest fails

### ISSUE THREAD

**Issue by Tilix4** [ynput/OpenPype#2583] opened 2022-01-24 13:35 UTC
**Describe the bug**
Using blender, I want to update the modeling in my rigging scene, I get the following error message:
```
Traceback (most recent call last):

  File "/home/felix/Downloads/OpenPype/build/exe.linux-x86_64-3.7/repos/avalon-core/avalon/blender/ops.py", line 102, in execute
    result = callback(*args, **kwargs)

  File "<string>", line 248, in exec_update

TypeError: BlendDataLibraries.remove(): error with argument 1, "library" -  Function.library does not support a 'None' assignment Library type
```

**To Reproduce**
1. Create a basic model in modeling task
2. Rig the model in rigging
3. Update the model and publish a v002
4. In rigging scene, go to `Manage` and try to `Update to latest`
5. The error is raised

**Expected behavior**
I want the model to be updated correctly on the current rig.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Host: Blender 2.93
 - OpenPype: 3.8.0-nightly.5

[cuID:[OP-2487](https://app.clickup.com/t/23ryjzc)]

**Comment by BigRoy** [comment] 2022-01-24 13:49
The stack trace doesn't point to the right code location, so for completeness it's referring to [this line 248](https://github.com/pypeclub/OpenPype/blob/2204b15ae1a29c754d16204bbcb1ef1ea73b37b9/openpype/hosts/blender/plugins/load/load_model.py#L248).

**Comment by Tilix4** [comment] 2022-01-24 15:34
@BigRoy Do you have any tip about what causes it? I'm about to try to fix it.

**Comment by BigRoy** [comment] 2022-08-19 12:40
> Do you have any tip about what causes it? I'm about to try to fix it.

Unfortunately I don't use blender myself. :)
Any chance this issue has been resolved since original post?

**Comment by LiborBatek** [comment] 2024-01-15 07:33
@simonebarbieri this not being an issue in the latest OP version , so could be closed I guess??

**Comment by BigRoy** [comment] 2024-07-03 21:34
I'll close this as it's been in backlog a long time ago, and Libor already mentioned failing to reproduce it. If it's still an issue in Ayon Blender report it on  [`ayon-blender`](https://github.com/ynput/ayon-blender) please.

**Closed by BigRoy** 2024-07-03 21:34 UTC
Labels: type: bug, host: Blender, community contribution
