### ISSUE TITLE
Enhancement: Publisher Action Completion Feedback.

### ISSUE THREAD

**Issue by tokejepsen** [ynput/OpenPype#5552] opened 2023-09-01 14:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

When using the new publisher to run actions like `repair`, there is no visual feedback for a successful run of the action.

### How would you imagine the implementation of the feature?

Similar to the `refresh` we could have `[action] completed successfully`.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

**Comment by BigRoy** [comment] 2023-09-01 14:20
I'm pretty sure this is a duplicate of this issue: https://github.com/ynput/OpenPype/issues/4036

**Closed** 2023-09-01 15:15 UTC
Labels: type: enhancement
