### ISSUE TITLE
Guard against running multiple syncs

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#1846] opened 2021-07-23 08:14 UTC
### Problem

When multiple instances of OpenPype are running logged under same ftrack user, that user will see duplicated action in ftrack. When such action is executed it will run twice (or as many as there are logged OpenPype instances running). The greatest danger pose those actions that are modifying database - Sync to Avalon. That one will create duplicate assets in avalon database.

### Proposal

We should lock syncing so no more then one such action can run at the same time (this is probably problem with other cases not directly related to multiple instances with same ftrack user - I suppose there can be more users running this action at the same time). This syncing issue is probably the most dangerous of those cases but it is rather confusing to see doubled actions, launching Maya 2x times and so on, so we should handle this more gracefully.

We already have local ID like *holistic-heavenly-skylark* generated per machine per user. We should add to this process ID of running OpenPype and use it as a lock. We can probably do little with different instance running on different machine under same user, but we should at least provide warning dialog or something.

[cuID:PYPE-1313]

**Comment by mkolar** [comment] 2022-06-07 22:15
I'm not sure this one is worth the effort at the moment. @antirotor have you seen this happen in real production?

**Comment by antirotor** [comment] 2022-06-07 22:19
> I'm not sure this one is worth the effort at the moment. @antirotor have you seen this happen in real production?

Yes, it happened in running production. Main problem is, that it has potential to wreak havoc in database. Might be solver (or partially solved by #1867)

**Comment by BigRoy** [comment] 2023-04-13 12:54
> When multiple instances of OpenPype are running logged under same ftrack user, that user will see duplicated action in ftrack. 

I saw this issue and was like "Oh, is that dangerous?" Our artists apparently quite frequently see e.g. everything duplicated 2x or 3x in the Actions pop-up in Ftrack - even when only a single OpenPype instance is running locally.

What I found out just now is that if the user is logged in on multiple machines (we frequently have an artist working on two or three machines during certain moments) that in Ftrack the actions show more than once. So it's not about having OpenPype launched multiple times on one machine, but even about it being launched across multiple machines. Making this much more likely to occur?

Note that we use manual syncing all the time (no sync server running) and so far have never seen duplicated assets, etc. However, the duplicated Actions is definitely an ongoing annoyance to our team.

**Comment by BigRoy** [comment] 2023-04-24 19:07
@antirotor Do you have any pointers on where this could potentially get fixed in the code? I'm not entirely sure where to look.

**Comment by antirotor** [comment] 2023-04-24 20:22
> @antirotor Do you have any pointers on where this could potentially get fixed in the code? I'm not entirely sure where to look.

This is old one. Partly fixed by work of @iLLiCiTiT  anyway. I  am not sure of its status. I think some of it couldn't be fixed because it would mean total rewrite of sync2avalon. We haven't heard of any problems related to it for long time. With AYON it shouldn't matter anymore, or should it @iLLiCiTiT ?

**Comment by BigRoy** [comment] 2023-04-24 20:41
For me the issue is what I reported [here](https://github.com/ynput/OpenPype/issues/1846#issuecomment-1506916393). Not entirely sure if the same issue but it sounded like the same thing.

**Comment by iLLiCiTiT** [comment] 2023-04-25 08:32
Actions running on artists machines are safe, they have unique identifiers. But for server actions it still could be an issue.

**Comment by BigRoy** [comment] 2023-04-25 08:35
Maybe I should open a different issue, but what I'm referring to is that **Users are seeing actions duplicated**. So they would for example see four times the "Admin" section or the "Sync" action if their particular ftrack user was logged into OpenPype Ftrack module across four different machines. It'd be great if somehow it would only show the actions for the current machine you're working on.

**Comment by iLLiCiTiT** [comment] 2023-04-25 08:38
> It'd be great if somehow it would only show the actions for the current machine you're working on.

It would be, but impossible. There is no way how to get the information where the actions are showed.

**Closed** 2023-09-08 14:37 UTC
Labels: type: bug, module: Ftrack
