### ISSUE TITLE
Maya override viewport options causes model panel to not be found

### ISSUE THREAD

**Issue by lucanvisuals** [ynput/OpenPype#4104] opened 2022-11-18 09:11 UTC
**Running version**
3.14.6

Maya override viewport options causes model panel to not be found. 
When toggling this to false in Studio settings, `project_settings/maya/publish/ExtractPlayblast/capture_preset/Viewport Options/override_viewport_options`, Thumbnail extraction fails on the review instance do to not finding an active panel.

openpype\vendor\python\common\capture.py 
line 455

**To Reproduce**
1. Toggle `project_settings/maya/publish/ExtractPlayblast/capture_preset/Viewport Options/override_viewport_options` to False
2. Create Review instance in Maya with camera.
3. Click the Playblast viewport just to be sure.
4. Publish Review
5. See error

**Expected behavior**
It should follow through extracting thumbnail and create burnins

**Screenshots**
![image](https://user-images.githubusercontent.com/104215675/202664391-4d13c4ac-2aca-42ce-aae1-c321c442534b.png)
![image (1)](https://user-images.githubusercontent.com/104215675/202664472-cbe84b19-1d6c-4ee1-9faa-39ddf7ffe156.png)

**Desktop:**
 - OS: Windows10 21H2 19044.2251
 - Host: Maya

[cuID:OP-4463]

**Comment by tokejepsen** [comment] 2022-11-18 09:16
Could you post the error message from the publish window as well?

**Comment by lucanvisuals** [comment] 2022-11-18 09:51
![image](https://user-images.githubusercontent.com/104215675/202672992-89c50239-fbe3-49d9-819b-85dcba4797d5.png)
![image](https://user-images.githubusercontent.com/104215675/202673040-c283e5a1-92cd-404c-ae36-363c46ebfc7b.png)

**Comment by m-u-r-p-h-y** [comment] 2022-11-18 13:53
duplicate of #3754  ?

**Comment by lucanvisuals** [comment] 2022-11-19 05:38
It is related yeah, looks like the same code from a few versions back. 
We just wanted artists to use their own viewport settings at times for the review camera, but seems there is a biggar issue here.

**Closed** 2023-02-20 11:33 UTC
Labels: type: bug, host: Maya
