### ISSUE TITLE
Houdini: Add BGEO loader and publisher

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#3432] opened 2022-06-29 10:47 UTC
## Feature

Add **bgeo** (and it's derivatives **bgesc**, ...) Loader to Houdini. Add ability to publish **bgeo** from Houdini.

[cuID:OP-3202]

**Comment by BigRoy** [comment] 2022-06-29 11:32
I think this is a duplicate of #3098

**Closed** 2023-02-01 15:18 UTC
Labels: type: enhancement, host: Houdini
