### ISSUE TITLE
Bug: Unable to publish ass file from Maya in ayon

### ISSUE THREAD

**Issue by krishnaavril** [ynput/OpenPype#6050] opened 2023-12-13 14:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Unable to publish ass file from MAYA 2022.5 through ayon
![image](https://github.com/ynput/OpenPype/assets/61413765/1ce53163-0e59-466c-9f2d-3fabb4f58ddc)

### Expected Behavior:

Ass should successfully get submitted

### Version

3.17.7

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

Open Maya 2022.5 through ayon
Create Ass publish type by choosing use selection.
publish using ayon

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
DEBUG: Writing C:\Users\VENKAT~1.M\AppData\Local\Temp\pyblish_tmp_hvkqfenu\assAlien.ass with:
{'filename': 'C:\\Users\\VENKAT~1.M\\AppData\\Local\\Temp\\pyblish_tmp_hvkqfenu\\assAlien.ass', 'startFrame': 1001, 'endFrame': 1073, 'frameStep': 1.0, 'selected': True, 'asciiAss': False, 'shadowLinks': True, 'lightLinks': True, 'boundingBox': True, 'expandProcedurals': False, 'camera': '|ALN_SC_63_SH_0010_CameraABC_v002:ALN_SC_63_SH_0010_1001_1_1|ALN_SC_63_SH_0010_CameraABC_v002:ALN_SC_63_SH_0010_1001_1_1Shape1', 'mask': 61184}
DEBUG: Writing: []
DEBUG: Extracting ass sequence with: {'filename': 'C:\\Users\\VENKAT~1.M\\AppData\\Local\\Temp\\pyblish_tmp_hvkqfenu\\assAlien.ass', 'startFrame': 1001, 'endFrame': 1073, 'frameStep': 1.0, 'selected': True, 'asciiAss': False, 'shadowLinks': True, 'lightLinks': True, 'boundingBox': True, 'expandProcedurals': False, 'camera': '|ALN_SC_63_SH_0010_CameraABC_v002:ALN_SC_63_SH_0010_1001_1_1|ALN_SC_63_SH_0010_CameraABC_v002:ALN_SC_63_SH_0010_1001_1_1Shape1', 'mask': 61184}
Traceback (most recent call last):
File "C:\Users\venkatasiva.m\AppData\Local\Ynput\AYON\dependency_packages\ayon_2310271602_windows.zip\dependencies\pyblish\plugin.py", line 527, in __explicit_process
runner(*args)
File "C:\Users\venkatasiva.m\AppData\Local\Ynput\AYON\addons\openpype_3.17.7-nightly.7\openpype\hosts\maya\plugins\publish\extract_arnold_scene_source.py", line 74, in process
instance.data["contentMembers"], attribute_data, kwargs
File "C:\Users\venkatasiva.m\AppData\Local\Ynput\AYON\addons\openpype_3.17.7-nightly.7\openpype\hosts\maya\plugins\publish\extract_arnold_scene_source.py", line 192, in _extract
exported_files = cmds.arnoldExportAss(**kwargs)
File "C:\Users\venkatasiva.m\AppData\Local\Ynput\AYON\addons\openpype_3.17.7-nightly.7\openpype\hosts\maya\plugins\publish\extract_arnold_scene_source.py", line 2, in arnoldExportAss
RuntimeError: arnoldExportAss -selected needs an active selection or a list of objects
```

[cuID:[OP-7601](https://app.clickup.com/t/86bwtdyu4)]

**Comment by BigRoy** [comment] 2023-12-13 14:57
You also shared this JSON report on discord:

[publish-report-231213-17-56.json.json](https://github.com/ynput/OpenPype/files/13662105/publish-report-231213-17-56.json.json)

It doesn't find any members to export:
```
DEBUG: Writing: []
```
Which is logged as empty from here: https://github.com/ynput/OpenPype/blob/2b951d29f23916e3354ecb6a328452dbf24d5282/openpype/hosts/maya/plugins/publish/extract_arnold_scene_source.py#L184


According to [this it only allows nodes that are transforms with shapes](https://github.com/ynput/OpenPype/blob/2b951d29f23916e3354ecb6a328452dbf24d5282/openpype/hosts/maya/plugins/publish/extract_arnold_scene_source.py#L139C47-L148
). And since the nodes passed to the extract are the exact set members: https://github.com/ynput/OpenPype/blob/2b951d29f23916e3354ecb6a328452dbf24d5282/openpype/hosts/maya/plugins/publish/extract_arnold_scene_source.py#L73-L75

**Make sure to put into the instance the transforms of the meshes themselves, not parent hierarchy.** So no parent groups, but the direct transforms of the meshes.

---

I believe @tokejepsen implemented the logic - so why it behaves like that is best referred to him.

But looking at the logic I suspect if you just select the geo in the viewport and drop that into the instance that it might likely export it.

**Comment by BigRoy** [comment] 2024-07-29 18:12
I believe this has been fixed since. @krishna8008 can you confirm latest AYON versions have this resolved?

**Comment by krishna8008** [comment] 2024-07-29 18:32
I can confirm this issue was resolved in latest AYON in Maya, Thank you @BigRoy

**Closed as completed by krishna8008** 2024-07-29 18:32 UTC
Labels: type: bug, community contribution
